#!/bin/bash
python3 -c 'print(__import__("4-square").__doc__)'
python3 -c 'print(__import__("4-square").Square.__doc__)'
python3 -c 'print(__import__("4-square").area.__doc__)'
python3 -c 'print(__import__("4-square").Square.area.__doc__)'
